CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS generals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    faction VARCHAR(20),
    is_lord BOOLEAN NOT NULL DEFAULT FALSE,
    starts_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    initial_hp INT,
    max_hp INT,
    initial_armor INT,
    max_armor INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_generals_name ON generals (name);
CREATE UNIQUE INDEX IF NOT EXISTS uk_generals_image_path ON generals (image_path);

ALTER TABLE generals ADD COLUMN IF NOT EXISTS initial_hp INT;
ALTER TABLE generals ADD COLUMN IF NOT EXISTS max_hp INT;
ALTER TABLE generals ADD COLUMN IF NOT EXISTS initial_armor INT;
ALTER TABLE generals ADD COLUMN IF NOT EXISTS max_armor INT;

CREATE TABLE IF NOT EXISTS identity_modes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    builtin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_identity_modes_name ON identity_modes (name);

CREATE TABLE IF NOT EXISTS identity_mode_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode_id BIGINT NOT NULL,
    player_count INT NOT NULL,
    identity_name VARCHAR(20) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    general_pool_size INT NOT NULL DEFAULT 2,
    is_leader BOOLEAN NOT NULL DEFAULT FALSE,
    identity_visible BOOLEAN NOT NULL DEFAULT FALSE,
    allow_lord_general BOOLEAN NOT NULL DEFAULT FALSE,
    same_identity_general_visible BOOLEAN NOT NULL DEFAULT FALSE,
    initial_hp_bonus INT NOT NULL DEFAULT 0,
    max_hp_bonus INT NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_identity_mode_rules_name ON identity_mode_rules (mode_id, player_count, identity_name);
CREATE INDEX IF NOT EXISTS idx_identity_mode_rules_mode_count ON identity_mode_rules (mode_id, player_count);

ALTER TABLE identity_mode_rules ADD COLUMN IF NOT EXISTS general_pool_size INT NOT NULL DEFAULT 2;
ALTER TABLE identity_mode_rules ADD COLUMN IF NOT EXISTS same_identity_general_visible BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key VARCHAR(64) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_settings (setting_key, setting_value)
SELECT 'manual_pick_enabled', 'false'
WHERE NOT EXISTS (
    SELECT 1 FROM app_settings WHERE setting_key = 'manual_pick_enabled'
);

INSERT INTO app_settings (setting_key, setting_value)
SELECT 'crown_prince_enabled', 'false'
WHERE NOT EXISTS (
    SELECT 1 FROM app_settings WHERE setting_key = 'crown_prince_enabled'
);

MERGE INTO identity_modes (name, enabled, builtin)
KEY(name)
VALUES ('标准身份局', TRUE, TRUE);

MERGE INTO identity_mode_rules
(mode_id, player_count, identity_name, quantity, is_leader, identity_visible, allow_lord_general, initial_hp_bonus, max_hp_bonus, sort_order)
KEY(mode_id, player_count, identity_name)
VALUES
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 2, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 2, '反贼', 1, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 3, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 3, '忠臣', 1, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 3, '反贼', 1, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 4, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 4, '忠臣', 1, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 4, '反贼', 1, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 4, '内奸', 1, FALSE, FALSE, FALSE, 0, 0, 40),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 5, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 5, '忠臣', 1, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 5, '反贼', 2, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 5, '内奸', 1, FALSE, FALSE, FALSE, 0, 0, 40),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 6, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 6, '忠臣', 1, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 6, '反贼', 3, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 6, '内奸', 1, FALSE, FALSE, FALSE, 0, 0, 40),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 7, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 7, '忠臣', 2, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 7, '反贼', 3, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 7, '内奸', 1, FALSE, FALSE, FALSE, 0, 0, 40),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 8, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 8, '忠臣', 2, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 8, '反贼', 4, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 8, '内奸', 1, FALSE, FALSE, FALSE, 0, 0, 40),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 9, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 9, '忠臣', 3, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 9, '反贼', 4, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 9, '内奸', 1, FALSE, FALSE, FALSE, 0, 0, 40),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 10, '主公', 1, TRUE, TRUE, TRUE, 1, 1, 10),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 10, '忠臣', 3, FALSE, FALSE, FALSE, 0, 0, 20),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 10, '反贼', 4, FALSE, FALSE, FALSE, 0, 0, 30),
((SELECT id FROM identity_modes WHERE name = '标准身份局'), 10, '内奸', 2, FALSE, FALSE, FALSE, 0, 0, 40);
